#!/usr/bin/env python3
"""Generate command-map.svg: every seed command, one row each, as a small
subcard (its signature) with the plain-language "what it actually does"
description running to the right of that subcard -- grouped under a header
per docs/commands/<slug>.md family, packed into two balanced columns
instead of one long single-column page.

Content is imported from generate_family_commands.py's own FAMILIES data
rather than duplicated here -- that module already has every command's
signature, description, and danger flag, hand-transcribed from each
docs/commands/<slug>.md page. This diagram just re-renders that same data
in a different shape (one wide row per command instead of one card per
family-<slug>.svg page) and ignores the folder-target fields entirely (see
below for why).

Two earlier shapes of this diagram are worth knowing about, because the
current one exists specifically because they didn't work:

  1. Commands on the left, connected by an arrow into the part of
     ~/seedling they read or write, on the right -- first with curved
     bezier arrows, then with orthogonal (horizontal/vertical-only) arrows
     each on their own dedicated lane so no two lines shared a path. Either
     way, ten-plus command families feeding a handful of folders is a lot
     of line traffic through one narrow corridor, and it made the diagram
     harder to read, not easier.
  2. Dropping the folder-tree side and packing every family into a
     multi-column masonry grid of summary cards -- commands were combined
     back into comma-separated groups per row ("venv, venv-list") to keep
     each card short, which meant the diagram no longer showed what any
     individual command actually did, undoing the main value of having
     per-command descriptions in the first place.

This version gives every individual command its own row (no more
combining several commands into one line) and puts the description where
there's room for it to actually be read. It started as a single column,
which meant a lot of vertical scrolling for eleven families' worth of
commands; splitting into two columns halves that, using the same greedy
shortest-column-first packing generate_command_map.py's own masonry-grid
predecessor used -- a whole family always stays in one column (never split
mid-family across the gap), tallest families packed first so a tall one
never lands in an already-tall column late in the pack.

Descriptions are re-wrapped at render time to fit each column's own width
(computed from each command's own desc_lines, joined back into one string)
rather than reusing generate_family_commands.py's own line breaks, which
were chosen for a still-different (single, wider) card width.

Not per-profile, so it isn't generated by generate_profile_flows.py --
run directly:

    python docs/diagrams/generate_command_map.py
"""

from __future__ import annotations

from pathlib import Path

from generate_family_commands import FAMILIES
from generate_profile_flows import DEFS, ICE, NAVY, SLATE, WHITE, esc, header

DANGER = "#9C4A3C"
DANGER_TINT = "#F5E8E5"
FONT_MONO = "Consolas, 'SF Mono', Monaco, 'Courier New', monospace"
OUT_DIR = Path(__file__).parent

NUM_COLS = 2
COL_GAP = 60
G_X = 40
SUB_W = 300
DESC_GAP = 24
DESC_W = 480
COL_CONTENT_W = SUB_W + DESC_GAP + DESC_W
CANVAS_W = G_X + NUM_COLS * COL_CONTENT_W + (NUM_COLS - 1) * COL_GAP + 40

SUB_H = 30
ROW_GAP = 10
DESC_SIZE = 12.5
DESC_LINE_H = 17
FAMILY_GAP = 34
FAMILY_HEAD_H = 54
TABLE_TOP = 128


def _wrap(text: str, max_chars: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    cur = ""
    for w in words:
        candidate = f"{cur} {w}".strip()
        if len(candidate) > max_chars and cur:
            lines.append(cur)
            cur = w
        else:
            cur = candidate
    if cur:
        lines.append(cur)
    return lines


def _desc_wrap_chars() -> int:
    # ~6.3px/char at DESC_SIZE Arial regular -- matches the estimate used
    # elsewhere in this diagram set for the same font/size combination.
    return int(DESC_W / 6.3)


def _row_height(desc_lines: list[str]) -> float:
    desc_h = len(desc_lines) * DESC_LINE_H
    return max(SUB_H, desc_h)


def _render_row(svg: list, x: float, y: float, signature: str, desc_lines: list[str], danger: bool) -> None:
    fill = DANGER_TINT if danger else ICE
    stroke = DANGER if danger else NAVY
    text_fill = DANGER if danger else NAVY
    row_h = _row_height(desc_lines)
    sub_y = y + (row_h - SUB_H) / 2
    svg.append(f'<rect x="{x:.0f}" y="{sub_y:.0f}" width="{SUB_W:.0f}" height="{SUB_H:.0f}" rx="8" fill="{fill}" stroke="{stroke}" stroke-width="1" opacity="0.95"/>')
    svg.append(f'<text x="{x+12:.0f}" y="{sub_y+SUB_H/2+4.5:.0f}" font-family="{FONT_MONO}" font-size="12.5" font-weight="700" fill="{text_fill}">{esc(signature)}</text>')
    desc_x = x + SUB_W + DESC_GAP
    desc_y0 = y + (row_h - len(desc_lines) * DESC_LINE_H) / 2 + DESC_LINE_H - 5
    for i, line in enumerate(desc_lines):
        svg.append(f'<text x="{desc_x:.0f}" y="{desc_y0 + i*DESC_LINE_H:.0f}" class="body" font-size="{DESC_SIZE}" fill="{SLATE}">{esc(line)}</text>')


def build() -> None:
    max_chars = _desc_wrap_chars()

    # Flatten each family's sections into one ordered list of
    # (signature, desc_lines, danger) rows -- section labels ("Create &
    # switch", "Packages", "Danger zone") from the per-family diagrams
    # aren't repeated here; family + danger tint already carries that.
    families = []
    for _, title, subtitle, _targets, _danger_targets, _whole_tree, sections in FAMILIES:
        rows = []
        for _label, items in sections:
            for signature, desc_lines, danger, _arrow_targets in items:
                wrapped = _wrap(" ".join(desc_lines), max_chars)
                rows.append((signature, wrapped, danger))
        families.append((title, subtitle, rows))

    heights = []
    for _, _, rows in families:
        h = FAMILY_HEAD_H
        for _, desc_lines, _ in rows:
            h += _row_height(desc_lines) + ROW_GAP
        heights.append(h)

    # Greedy shortest-column-first pack, tallest families placed first so a
    # tall one never lands in an already-tall column late in the pack. Each
    # family stays whole in one column -- never split across the gap.
    pack_order = sorted(range(len(families)), key=lambda i: -heights[i])
    col_heights = [0.0] * NUM_COLS
    col_items: list[list[int]] = [[] for _ in range(NUM_COLS)]
    for i in pack_order:
        c = min(range(NUM_COLS), key=lambda c: col_heights[c])
        col_items[c].append(i)
        col_heights[c] += heights[i] + FAMILY_GAP

    # Within each column, restore original family order so the page still
    # reads top-to-bottom the way docs/COMMANDS.md lists families.
    for c in range(NUM_COLS):
        col_items[c].sort()

    canvas_h = TABLE_TOP + max(col_heights) + 30

    svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS_W} {canvas_h:.0f}" font-family="Arial, Helvetica, sans-serif">']
    svg.append(f"<defs>{DEFS}</defs>")
    svg.append(f'<rect x="0" y="0" width="{CANVAS_W}" height="{canvas_h:.0f}" fill="{WHITE}"/>')
    svg.append(header("Every seed command, in full",
                      "One row per command -- what it does, to the right of its name"))

    for c in range(NUM_COLS):
        col_x = G_X + c * (COL_CONTENT_W + COL_GAP)
        y = TABLE_TOP
        for i in col_items[c]:
            title, subtitle, rows = families[i]
            h = heights[i]
            svg.append(f'<text x="{col_x:.0f}" y="{y+16:.0f}" class="head fg" font-size="17" font-weight="700">{esc(title)}</text>')
            svg.append(f'<text x="{col_x:.0f}" y="{y+32:.0f}" class="body fmute" font-size="11" font-style="italic">{esc(subtitle)}</text>')
            svg.append(f'<line x1="{col_x:.0f}" y1="{y+40:.0f}" x2="{col_x+COL_CONTENT_W:.0f}" y2="{y+40:.0f}" stroke="{NAVY}" stroke-width="1" opacity="0.25"/>')
            ry = y + FAMILY_HEAD_H
            for signature, desc_lines, danger in rows:
                _render_row(svg, col_x, ry, signature, desc_lines, danger)
                ry += _row_height(desc_lines) + ROW_GAP
            y += h + FAMILY_GAP

    svg.append("</svg>")
    out_path = OUT_DIR / "command-map.svg"
    out_path.write_text("\n".join(svg), encoding="utf-8")
    print(f"wrote command-map.svg  ({CANVAS_W}x{canvas_h:.0f})")


if __name__ == "__main__":
    build()
