"""
seedling never assumes uv is on the user's PATH. The bootstrap installer
(install.sh / install.ps1) downloads uv straight into ~/seedling/bin, and
this module always calls that exact copy. This keeps seedling fully
self-contained: nothing "pre-installed" is required.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from . import PUBLIC_RAW_BASE, colors, config, paths


class UvNotFound(RuntimeError):
    pass


def tag_line(line: str) -> str:
    """Prefix a line of uv's own output so it's never mistaken for a message
    seedling printed itself. Blank lines pass through untouched."""
    if not line.strip():
        return line
    return f"{colors.dim('[uv]')} {line}"


def find_uv() -> Path:
    """Locate the sandboxed uv binary, falling back to PATH only as a last resort."""
    local = paths.uv_binary()
    if local.exists():
        return local

    on_path = shutil.which("uv")
    if on_path:
        return Path(on_path)

    raise UvNotFound(
        "uv was not found in ~/seedling/bin or on PATH.\n"
        "Re-run the seedling installer:\n"
        f"  bash:       curl -fsSL {PUBLIC_RAW_BASE}/installers/install.sh | sh\n"
        f"  powershell: irm {PUBLIC_RAW_BASE}/installers/install.ps1 | iex"
    )


def _as_mirror_url(value: str) -> str:
    """UV_PYTHON_INSTALL_MIRROR requires a URL; a plain directory path from
    the config (e.g. a network share of interpreter archives) is converted
    to a file:// URL. Values that already look like URLs pass through."""
    if "://" in value:
        return value
    normalized = value.replace("\\", "/")
    if len(normalized) >= 2 and normalized[1] == ":":  # windows drive path
        return f"file:///{normalized}"
    if normalized.startswith("/"):
        return f"file://{normalized}"
    return value


def _build_env(env: dict | None) -> dict:
    """The environment for every uv invocation:

    - uv's download/package cache is redirected into
      ~/seedling/system/cache/uv so it lives inside the seedling folder
      like everything else.
    - the `python_mirror` and `package_index` settings (seeded from
      seedling.conf at install time -- the offline/air-gapped story) are
      translated into uv's own environment knobs, so users never have to
      set UV_* variables themselves.

    Everything uses setdefault: explicit UV_* variables already in the
    user's environment still win."""
    full_env = os.environ.copy()
    if env:
        full_env.update(env)
    full_env.setdefault("UV_CACHE_DIR", str(paths.UV_CACHE_DIR))

    mirror = config.get("python_mirror")
    if mirror:
        full_env.setdefault("UV_PYTHON_INSTALL_MIRROR", _as_mirror_url(str(mirror)))

    index = config.get("package_index")
    if index:
        index = str(index)
        if "://" in index:
            full_env.setdefault("UV_DEFAULT_INDEX", index)
        else:
            # A plain directory of wheels: uv has no environment variable
            # for "flat directory index with the internet index disabled"
            # (UV_NO_INDEX isn't honored on all versions), but it does
            # honor a config file -- generate one and point uv at it.
            full_env.setdefault("UV_CONFIG_FILE", str(_offline_index_config(index)))
    return full_env


def _offline_index_config(index_dir: str) -> Path:
    """Writes (or refreshes) a uv.toml declaring `index_dir` as a flat
    default index -- uv then resolves packages from that directory of
    wheels ONLY, with pypi.org fully disabled. Kept alongside seedling's
    own config; regenerated whenever the setting changes."""
    content = (
        "# Generated by seedling from the `package_index` setting. Do not edit;\n"
        "# change it with:  seed config set package_index <url-or-directory>\n"
        "[[index]]\n"
        'name = "seedling-offline"\n'
        f'url = "{_as_mirror_url(index_dir)}"\n'
        'format = "flat"\n'
        "default = true\n"
    )
    cfg = paths.CONFIG_DIR / "uv.toml"
    try:
        if not cfg.exists() or cfg.read_text() != content:
            cfg.write_text(content)
    except OSError:
        pass  # uv will fail loudly if the file is genuinely unusable
    return cfg


def run(args: list[str], *, env: dict | None = None, check: bool = True) -> subprocess.CompletedProcess:
    """Runs uv, streaming its combined stdout/stderr live with a `[uv]` tag
    on every line so it reads distinctly from seedling's own print()s."""
    uv = find_uv()
    full_env = _build_env(env)
    cmd = [str(uv), *args]
    proc = subprocess.Popen(
        cmd, env=full_env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        sys.stdout.write(tag_line(line))
    proc.wait()
    if check and proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, cmd)
    return subprocess.CompletedProcess(cmd, proc.returncode)


def run_captured(args: list[str], *, env: dict | None = None, check: bool = True) -> subprocess.CompletedProcess:
    """Like run(), but captures stdout/stderr instead of streaming them
    live, so the caller can filter/inspect output before deciding what (if
    anything) to print. Used where uv's own messaging would be redundant or
    misleading given seedling's own folder conventions -- e.g. uv's
    "activate with: source .../activate" hint after `uv venv`, which doesn't
    match how `seed activate` actually works."""
    uv = find_uv()
    full_env = _build_env(env)
    return subprocess.run(
        [str(uv), *args], env=full_env, check=check,
        capture_output=True, text=True,
    )


def python_install_dir_env() -> dict:
    """Env override so `uv python install` lands under seedling's own tree
    instead of uv's default cache location."""
    return {"UV_PYTHON_INSTALL_DIR": str(paths.BASE_DIR)}


def tool_install_env() -> dict:
    """Env override so `uv tool install` (used to install/update seed-cli
    itself) keeps everything inside ~/seedling instead of uv's default
    per-user tool location."""
    return {
        "UV_TOOL_DIR": str(paths.TOOL_DIR),
        "UV_TOOL_BIN_DIR": str(paths.BIN_DIR),
    }
